discord:
  enabled: true
  token: "MTM3MDkxMTM1Njc3NzEzNjE3OA.GKMFG_.xPQmqGJH7bY-mhEIngGlbUVw3RVXNtyTyVTORQ"
  default-channel-id: "1370924918656729211"
  family-channels:
  # 각 가문별 채널 ID는 이곳에 저장됩니다
  # 예: family_name: "채널ID"
preventEnder: false  # 엔더 월드 진입 차단 여부 (true: 차단, false: 차단 안 함)