discord:
  enabled: true
  token: "디스코드_봇_토큰"
  default-channel-id: "기본_서버_채널_ID"
  family-channels:
  # 각 가문별 채널 ID는 이곳에 저장됩니다
  # 예: family_name: "채널ID"
preventEnder: false  # 엔더 월드 진입 차단 여부 (true: 차단, false: 차단 안 함)